name: meu_financeiro_android
description: "Minhas Finanças - App Android"
publish_to: 'none'
version: 1.0.0+1
google_sign_in: ^6.2.1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # UI
  fl_chart: ^0.69.0
  intl: ^0.19.0
  google_fonts: ^6.2.1

  # Utils
  provider: ^6.1.1
  google_sign_in: 6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true